processed 5 tasks

task 1 'run-graphql'. lines 6-28:
Response: {
  "data": {
    "availableRange": {
      "first": {
        "digest": "AJzWK6hiczp2eLtQCRmfa3aWawBRqhQcRmJi4jVYGWeb",
        "sequenceNumber": 0
      },
      "last": {
        "digest": "AJzWK6hiczp2eLtQCRmfa3aWawBRqhQcRmJi4jVYGWeb",
        "sequenceNumber": 0
      }
    },
    "first": {
      "digest": "AJzWK6hiczp2eLtQCRmfa3aWawBRqhQcRmJi4jVYGWeb",
      "sequenceNumber": 0
    },
    "last": {
      "digest": "AJzWK6hiczp2eLtQCRmfa3aWawBRqhQcRmJi4jVYGWeb",
      "sequenceNumber": 0
    }
  }
}

task 2 'create-checkpoint'. lines 30-30:
Checkpoint created: 1

task 3 'create-checkpoint'. lines 33-33:
Checkpoint created: 2

task 4 'run-graphql'. lines 36-58:
Response: {
  "data": {
    "availableRange": {
      "first": {
        "digest": "AJzWK6hiczp2eLtQCRmfa3aWawBRqhQcRmJi4jVYGWeb",
        "sequenceNumber": 0
      },
      "last": {
        "digest": "7xfrGBR3RS2pCFNsBFtVyRsWCRPZi59c9t4Ltfjar9m7",
        "sequenceNumber": 2
      }
    },
    "first": {
      "digest": "AJzWK6hiczp2eLtQCRmfa3aWawBRqhQcRmJi4jVYGWeb",
      "sequenceNumber": 0
    },
    "last": {
      "digest": "7xfrGBR3RS2pCFNsBFtVyRsWCRPZi59c9t4Ltfjar9m7",
      "sequenceNumber": 2
    }
  }
}
